export const characters = [
    'Werewolf',
    'Vampire',
    'Zombie',
    'Frankenstein',
    'Alien',
    'King Kong',
    'Godzilla',
    'Mummy',
    'Spider',
    'Witch',
    'Ghost',
    'Devil',
    'Rat',
    'Bats',
    'Justin Bieber',
    'Clown',
    'Snake',
    'Wolf',
    'Pirate',
    'Voldemort',
    'Darth Vader',
    'Ghostbuster',
    'Big Foot',
    'T-Rex',
    'Chicken',
    'Hulk',
    'Michael Jackson',
    'Shrek',
    'Dragon',
    'Goat',
    'Girrafe',
    'Donald Trump',
    'Camel',
    'Human',

];

export const actions = [
    'Eating Candy',
	'Eating Donut',
    'Eating Banana',
    'Eating Corn',
    'Drawing Pumpkin',
	'Drawing Marshmallow',
    'Is Laughing',
    'Is Crawling',
    'Is Bowling',
    'Dancing Ballet',
    'Is Twerking',
    'Doing Push Ups',
    'Is Hugging',
    'Headbutt',
    'Doing Squats',
    'Doing Kung Fu',
    'Playing Basketball',
    'Playing UNO Card Game',
	'Drinking Coffee',
	'Milking Cow',
	'Doing Yoga',
	'Washing Shoes',
	'Putting Sun Tan Lotion',
	'Cutting Hair',
	'Reading Newspaper',
	'Is Swimming',
    'Doing Sit Ups',
    'Eating Hot Dog',
    'Looking At Mirror',
    'Is Boxing',
    'Pointing Up',
    'Biting Apple',
    'Is Unemployed',
    'Is Energetic',
    'Is Tired',
    'Is Hungry',
    'Wants To Poop',
    'Is Pooping',
    'Is Speaking French',
    'Is Speaking Chinese',
    'Is Speaking Malay',
    'Is Dead',
    'Is Programming',
    'Is Sad',
    'Is Sexy',
    'Is Married',
    'Is Jogging',
    'Skipping Rope',
    'Cleaning Toilet',
    'Eating Ramen',
    'Eating Mango Sticky Rice',
    'Eating Burger',
    'Is Slapping Face',
    'Running On A Hill',
    'Chased By Zebra',
    'And Friends',
    'The Explorer',
];